name: Check SSH Keys
on: [push, pull_request]

jobs:
  check-ssh-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify SSH Keys
        run: |
          for key_file in $(ls /keys/*.pub); do
            key_info=$(ssh-keygen -l -f $key_file)
            if [[ $key_info == *"RSA"* && $key_info == *"2048"* ]]; then
              echo "RSA key (2048-bit): $key_file"
            elif [[ $key_info == *"ED25519"* && $key_info == *"4096"* ]]; then
              echo "ED25519 key (4096-bit): $key_file"
            else
              echo "Invalid key: $key_file"
            fi
          done
